volumes:
  postgres_test_catalog_data:
  localstack_test_catalogue_data:

networks:
  catalogue-test-system-network:
    external: false

services:
  localstack-catalogue-test:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-catalogue-test}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEFAULT_REGION=${DEFAULT_REGION-us-east-1}
      - SERVICES=${SERVICES-lambda,s3,apigateway,cloudwatch,dynamodb,sqs,kinesis,serverless,secretsmanager}
      - EDGE_PORT=4566
      - DATA_DIR=${DATA_DIR-./data}:/tmp/localstack
      - DEBUG=${DEBUG-}message_handler_service
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - "localstack_test_catalogue_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - catalogue-test-system-network

  postgres-catalogue-test:
    image: postgres:16.0-alpine
    hostname: postgres-catalogue-test
    ports:
      - "5432:5432"
    env_file:
      - .env.test.template
    volumes:
      - postgres_test_catalog_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - catalogue-test-system-network

  migrations-catalogue-test:
    build: .
    volumes:
      - .:/app/
    env_file:
      - .env.test.template
    command: bash -c "while !</dev/tcp/postgres-catalogue-test/5432; do sleep 1; done; alembic -c migrations/alembic/alembic.ini upgrade head"
    networks:
      - catalogue-test-system-network

  catalogue-app-test:
    build: .
    volumes:
      - .:/app/
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8180:8080"
    env_file:
      - .env.test.template
    networks:
      - catalogue-test-system-network

  catalogue-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app/
    command: python -m pytest -s -vv -x --cov --cov-report=html:/app/reports/coverage
    depends_on:
      - postgres-catalogue-test
    env_file:
      - .env.test.template
    networks:
      - catalogue-test-system-network

  catalogue-bdd:
    build:
      context: ./test_bdd
      dockerfile: Dockerfile.bdd
    volumes:
      - ./test_bdd:/app/
    command: behave
    networks:
      - catalogue-test-system-network
    environment:
      - BASE_URL=http://catalogue-app-test:8080
