CREATE DATABASE "catalogue";

CREATE USER catalogue_app WITH PASSWORD '123abc';

GRANT ALL PRIVILEGES ON DATABASE "catalogue" TO catalogue_app;

\c catalogue
GRANT ALL PRIVILEGES ON SCHEMA public TO catalogue_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO catalogue_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO catalogue_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO catalogue_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO catalogue_app;
